In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
import numpy as np
arr=np.ones((3,2))

In [6]:
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [9]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [10]:
arr=np.full((4,5),2)

In [11]:
arr

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [12]:
arr=np.full((4,5),2.8)
arr

array([[2.8, 2.8, 2.8, 2.8, 2.8],
       [2.8, 2.8, 2.8, 2.8, 2.8],
       [2.8, 2.8, 2.8, 2.8, 2.8],
       [2.8, 2.8, 2.8, 2.8, 2.8]])

In [13]:
np.random.random((2,3))

array([[0.23321699, 0.627799  , 0.56411609],
       [0.40794863, 0.44129411, 0.13594625]])

In [15]:
a=np.array([[2,3,4],[4,4,6]])
print(a.shape)

(2, 3)


In [1]:
#20 minutte video run hoiche class 13(numpy theory)


In [3]:
import numpy as np
s=np.array([[1,2,3,4],[2,3,4,5],[6,7,8,9]])
print(s.shape)

(3, 4)


In [4]:
a=np.array([[2,3,4,4],[2,4,5,6]])
b=np.array([[2,3,4],[4,4,6]])

In [6]:
b.shape=(3,2)
print(b)

[[2 3]
 [4 4]
 [4 6]]


In [7]:
a.shape=(8,1)
print(a)

[[2]
 [3]
 [4]
 [4]
 [2]
 [4]
 [5]
 [6]]


In [8]:
a=np.arange(25)

In [9]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
print(a.size)

25


In [12]:
d=np.array([[1,2,3,4],[2,3,4,5],[6,7,8,9]])
d.size

12

In [14]:
a=np.arange(24,dtype=float)
print(a.dtype)
a

float64


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [15]:
np.sum([10,20])

30

In [17]:
a,b=10,20
np.sum([a,b])

30

In [18]:
#axis 0 hole index wise
np.sum([[1,2],[5,6]],axis=0)

array([6, 8])

In [19]:
#list wise sum axis 1
np.sum([[1,2],[5,6]],axis=1)


array([ 3, 11])

In [20]:
np.sum([[1,2],[5,6]])

14

In [22]:
np.subtract(10,20 )

-10

In [23]:
np.multiply(2,3)

6

In [24]:
np.divide(10,2)

5.0

In [25]:
a=np.array([2,4,6])
b=np.array([1,2,3])
np.multiply(a,b )

array([ 2,  8, 18])

In [26]:
print("Expotnet : ",np.exp(a))
print("Square root : ",np.sqrt(a))
print("Sin: ",np.sin(a))
print("Cos; ",np.cos(a))
print("Log : ",np.log(a))

Expotnet :  [  7.3890561   54.59815003 403.42879349]
Square root :  [1.41421356 2.         2.44948974]
Sin:  [ 0.90929743 -0.7568025  -0.2794155 ]
Cos;  [-0.41614684 -0.65364362  0.96017029]
Log :  [0.69314718 1.38629436 1.79175947]


In [27]:
a=[1,2,4]
b=[2,4,4]
c=[1,2,4]

In [28]:
np.equal(a,b)

array([False, False,  True])

In [29]:
np.array_equal(a,c)

True

In [30]:
np.array_equal(a,b)

False

In [32]:
a=[1,2,4]
b=[2,4,4]
c=[1,2,4]
print("Sum : ",np.sum(a))
print("Minimum Value : ",np.min(a))
print("Mean : ",np.mean(a))
print("Median : ",np.median(a))
print("Coorelation Coefficient : ",np.corrcoef(a))
print("Standard  : ",np.std(a))


Sum :  7
Minimum Value :  1
Mean :  2.3333333333333335
Median :  2.0
Coorelation Coefficient :  1.0
Standard  :  1.247219128924647


In [33]:
import numpy as np
a=np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b=np.array([[0,1,2]])
print("First array :\n",a,'\n')
print("second array : \n",b,'\n')
print("First array + Second Array : \n",a+b,'\n\n')

First array :
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

second array : 
 [[0 1 2]] 

First array + Second Array : 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 




In [34]:
a=['m','o','n','t','y',' ','p','y','t','h','o','n',]
a[2:9]

['n', 't', 'y', ' ', 'p', 'y', 't']

In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]

array([1, 2, 3])

In [36]:
a[:1]

array([[1, 2, 3]])

In [37]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
a[:1,1:]

array([[2, 3]])

In [39]:
a[:2,1:] 

array([[2, 3],
       [5, 6]])

In [40]:
a[:1][0][1:]

array([2, 3])

In [41]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [42]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [44]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
x=np.arange(16).reshape(4,4)
print(x,"\n\n")
print(np.hsplit(x,2))
print("\n\n",np.hsplit(x,np.array([2,3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [50]:
import numpy as np
import sys

l=range(1000)
print("Size of a list : ",sys.getsizeof(1)*len(l))

a=np.arange(1000)
print("Size of an array : ",a.size*a.itemsize)

Size of a list :  28000
Size of an array :  4000


In [52]:
import time
def using_List():
    t1=time.time()
    x=range(10000)
    y=range(10000)
    z=[x[i]+y[i] for i in range(len(x))]
    return time.time()-t1

def using_Numpy():
    t1=time.time()
    a=np.arange(10000)
    b=np.arange(10000)
    z=a+b
    return time.time()-t1

list_time=using_List()
numpy_time= using_Numpy()
print(list_time,numpy_time)
print("In this example Nymoy is "+str(list_time/numpy_time)+" times ")

0.002481222152709961 0.0


ZeroDivisionError: float division by zero

In [ ]:
#class 14 time 36 minutes